create extension if not exists pgcrypto;

do $$
begin
  create type public.match_status as enum ('scheduled', 'live', 'finished');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.admins (
  email text primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null,
  email text not null unique,
  has_paid boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  home_team text not null,
  away_team text not null,
  starts_at timestamptz not null,
  stage text not null default 'Fase de grupos',
  home_score integer,
  away_score integer,
  status public.match_status not null default 'scheduled',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint matches_non_negative_scores check (
    (home_score is null or home_score >= 0) and
    (away_score is null or away_score >= 0)
  ),
  constraint matches_finished_has_score check (
    status <> 'finished' or (home_score is not null and away_score is not null)
  )
);

create table if not exists public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  predicted_home_score integer not null,
  predicted_away_score integer not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, match_id),
  constraint predictions_non_negative_scores check (
    predicted_home_score >= 0 and predicted_away_score >= 0
  )
);

create table if not exists public.scoring_rules (
  id text primary key default 'default',
  result_points integer not null default 1,
  exact_bonus_points integer not null default 3,
  updated_at timestamptz not null default now(),
  constraint scoring_rules_non_negative check (result_points >= 0 and exact_bonus_points >= 0)
);

create table if not exists public.change_history (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  entity text not null,
  entity_id text not null,
  change_type text not null,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

insert into public.scoring_rules (id, result_points, exact_bonus_points)
values ('default', 1, 3)
on conflict (id) do nothing;

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, display_name, email)
  values (
    new.id,
    coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1)),
    new.email
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

drop trigger if exists touch_profiles_updated_at on public.profiles;
create trigger touch_profiles_updated_at
before update on public.profiles
for each row execute function public.touch_updated_at();

drop trigger if exists touch_matches_updated_at on public.matches;
create trigger touch_matches_updated_at
before update on public.matches
for each row execute function public.touch_updated_at();

drop trigger if exists touch_predictions_updated_at on public.predictions;
create trigger touch_predictions_updated_at
before update on public.predictions
for each row execute function public.touch_updated_at();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.admins
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

create or replace function public.match_outcome(home_score integer, away_score integer)
returns text
language sql
immutable
as $$
  select case
    when home_score > away_score then 'home'
    when home_score < away_score then 'away'
    else 'draw'
  end;
$$;

create or replace view public.leaderboard as
select
  profiles.id as profile_id,
  profiles.display_name,
  profiles.email,
  profiles.has_paid,
  coalesce(sum(
    case
      when matches.status = 'finished'
        and predictions.id is not null
        and public.match_outcome(predictions.predicted_home_score, predictions.predicted_away_score) =
            public.match_outcome(matches.home_score, matches.away_score)
      then rules.result_points
      else 0
    end +
    case
      when matches.status = 'finished'
        and predictions.predicted_home_score = matches.home_score
        and predictions.predicted_away_score = matches.away_score
      then rules.exact_bonus_points
      else 0
    end
  ), 0)::integer as points,
  count(*) filter (
    where matches.status = 'finished'
      and predictions.id is not null
      and public.match_outcome(predictions.predicted_home_score, predictions.predicted_away_score) =
          public.match_outcome(matches.home_score, matches.away_score)
  )::integer as correct_results,
  count(*) filter (
    where matches.status = 'finished'
      and predictions.predicted_home_score = matches.home_score
      and predictions.predicted_away_score = matches.away_score
  )::integer as exact_scores
from public.profiles
cross join public.scoring_rules rules
left join public.predictions on predictions.user_id = profiles.id
left join public.matches on matches.id = predictions.match_id
where rules.id = 'default'
group by profiles.id, profiles.display_name, profiles.email, profiles.has_paid
order by points desc, exact_scores desc, correct_results desc, profiles.display_name asc;

grant usage on schema public to authenticated;
grant select on public.leaderboard to authenticated;
grant select on public.admins to authenticated;
grant select, insert, update, delete on public.profiles to authenticated;
grant select, insert, update, delete on public.matches to authenticated;
grant select, insert, update, delete on public.predictions to authenticated;
grant select, update on public.scoring_rules to authenticated;
grant select, insert on public.change_history to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.admins enable row level security;
alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;
alter table public.scoring_rules enable row level security;
alter table public.change_history enable row level security;

drop policy if exists "admins can read admins" on public.admins;
create policy "admins can read admins"
on public.admins for select
to authenticated
using (public.is_admin());

drop policy if exists "profiles are visible to signed in users" on public.profiles;
create policy "profiles are visible to signed in users"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "users insert own profile" on public.profiles;
create policy "users insert own profile"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "users update own profile and admins update all" on public.profiles;
create policy "users update own profile and admins update all"
on public.profiles for update
to authenticated
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

drop policy if exists "admins delete profiles" on public.profiles;
create policy "admins delete profiles"
on public.profiles for delete
to authenticated
using (public.is_admin());

drop policy if exists "matches visible to signed in users" on public.matches;
create policy "matches visible to signed in users"
on public.matches for select
to authenticated
using (true);

drop policy if exists "admins manage matches" on public.matches;
create policy "admins manage matches"
on public.matches for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "users read own predictions and public locked predictions" on public.predictions;
create policy "users read own predictions and public locked predictions"
on public.predictions for select
to authenticated
using (
  user_id = auth.uid()
  or public.is_admin()
  or exists (
    select 1
    from public.matches
    where matches.id = predictions.match_id
      and matches.starts_at <= now()
  )
);

drop policy if exists "users insert own unlocked predictions" on public.predictions;
create policy "users insert own unlocked predictions"
on public.predictions for insert
to authenticated
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.matches
    where matches.id = predictions.match_id
      and matches.starts_at > now()
  )
);

drop policy if exists "users update own unlocked predictions" on public.predictions;
create policy "users update own unlocked predictions"
on public.predictions for update
to authenticated
using (
  user_id = auth.uid()
  and exists (
    select 1
    from public.matches
    where matches.id = predictions.match_id
      and matches.starts_at > now()
  )
)
with check (
  user_id = auth.uid()
  and exists (
    select 1
    from public.matches
    where matches.id = predictions.match_id
      and matches.starts_at > now()
  )
);

drop policy if exists "admins delete predictions" on public.predictions;
create policy "admins delete predictions"
on public.predictions for delete
to authenticated
using (public.is_admin());

drop policy if exists "rules visible to signed in users" on public.scoring_rules;
create policy "rules visible to signed in users"
on public.scoring_rules for select
to authenticated
using (true);

drop policy if exists "admins update rules" on public.scoring_rules;
create policy "admins update rules"
on public.scoring_rules for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "admins read history" on public.change_history;
create policy "admins read history"
on public.change_history for select
to authenticated
using (public.is_admin());

drop policy if exists "admins write history" on public.change_history;
create policy "admins write history"
on public.change_history for insert
to authenticated
with check (public.is_admin());
